### ISSUE TITLE
function FontMetrics.to_binary/1 is undefined

### ISSUE THREAD

**Issue by Hermanverschooten** [boydm/truetype_metrics#1]
I tried to run this on a couple of fonts, but it complains about the module FontMetrics not being available. I tried on Elixir 1.8.1 with Erlang 21, and 1.9.0 with Erlang 22.

```
mix archive.install hex truetype_metrics

Resolving Hex dependencies...
Dependency resolution completed:
New:
  font_metrics 0.3.1
  msgpax 2.2.3
  truetype_metrics 0.3.0
* Getting truetype_metrics (Hex package)
* Getting font_metrics (Hex package)
* Getting msgpax (Hex package)
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  font_metrics 0.3.1
  msgpax 2.2.3
All dependencies are up to date
==> msgpax
Compiling 8 files (.ex)
Generated msgpax app
==> font_metrics
Compiling 2 files (.ex)
Generated font_metrics app
==> truetype_metrics
Compiling 2 files (.ex)
Generated truetype_metrics app
Generated archive "truetype_metrics-0.3.0.ez" with MIX_ENV=prod
Are you sure you want to install "truetype_metrics-0.3.0.ez"? [Yn] y
* creating /Users/herman/.asdf/installs/elixir/1.8.1-otp-21/.mix/archives/truetype_metrics-0.3.0
MacBookPro➜  pdf  mix truetype_metrics /usr/local/Caskroom/font-meslo-for-powerline/2015-12-04/fonts-2015-12-04/AnonymousPro/Anonymice\ Powerline\ Bold\ Italic.ttf

Generating metrics for /usr/local/Caskroom/font-meslo-for-powerline/2015-12-04/fonts-2015-12-04/AnonymousPro/Anonymice Powerline Bold Italic.ttf

** (UndefinedFunctionError) function FontMetrics.to_binary/1 is undefined (module FontMetrics is not available)
    FontMetrics.to_binary(%{__struct__: FontMetrics, ascent: 1675, descent: -373, direction: 2, kerning: %{}, max_box: {-281, -395, 1373, 1866}, metrics: %{263 => -31, 105 => -20, 313 => -49, 296 => -49, 48 => 242, 230 => 319, 343 => 49, 270 => -49, 344 => 26, 62 => 195, 205 => -49, 333 => -131, 232 => 571, 39 => -16, 164 => -8, 236 => 139, 217 => 31, 83 => 223, 265 => -184, 63 => -53, 287 => -49, 359 => -8, 372 => 68, 34 => -58, 248 => 55, 178 => -9, 181 => 57, 195 => -49, 254 => -35, 193 => 59, 68 => -127, 176 => -9, 365 => 0, 289 => 68, 78 => 186, 199 => -20, 351 => 365, 224 => -49, 52 => -9, 306 => -49, 212 => 57, 321 => -72, 288 => -119, ...}, smallest_ppem: 8, source: %{__struct__: FontMetrics.Source, created_at: #DateTime<2013-07-14 11:02:12Z>, file: "Anonymice Powerline Bold Italic.ttf", font_type: :true_type, modified_at: #DateTime<2013-07-14 11:02:12Z>, signature: "jMKnrnLojp8BHv0c2Mf1KFVe92Km6ZEktFMqdDx1gxY", signature_type: :sha256}, units_per_em: 2048, version: "0.1.0"})
    lib/mix/tasks/gen.ex:117: Mix.Tasks.TruetypeMetrics.gen_file/2
    lib/mix/tasks/gen.ex:87: Mix.Tasks.TruetypeMetrics.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

**Comment by boydm** [comment]
Yes. The FontMetrics package is also required. This is a bit of a pain and is easier when not done as an archive install.

You can fix this by also doing "mix archive.install hex font_metrics'

Or just clone the truetype repo and building (and running) it there.

**Comment by jessejanderson** [comment]
After fixing this FontMetrics issue, I then got:
```** (UndefinedFunctionError) function Msgpax.pack/1 is undefined (module Msgpax is not available)```

**Comment by jessejanderson** [comment]
I was able to fix by running `mix archive.install hex msgpax`.

**Comment by boydm** [comment]
Yes. That was the right thing to do. It is a bit unfortunate that dependencies in archives aren't brought in automatically.

**Comment by boydm** [comment]
As of Scenic v0.11 this will no longer be an issue as building a scenic ap will do this automatically without relying on an installed package.

**Comment by boydm** [comment]
Since serializing  the font metrics is no longer required by Scenic and well... there isn't really any good reason for the font_metrics library to have an opinion about a serialization format, I'm going to create a version 0.4 version of it without the serialization functionality. That should be handled by the caller.

0.3. will continue to have it in for compatibility sake.

**Comment by boydm** [comment]
closing the issue as it seems no longer relevant
